version: 2.1

orbs:
  node: circleci/node@5.1.0
  aws-s3: circleci/aws-s3@4.0.0

jobs:
  build:
    docker:
      - image: cimg/node:21.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build React App
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy:
    docker:
      - image: cimg/node:21.2.0
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - aws-s3/sync:
          from: /tmp/workspace/build
          to: 's3://$AWS_S3_BUCKET_NAME'
          arguments: '--acl public-read --delete'

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
